// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsopcfktfmrihmrvgxrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzb3BjZmt0Zm1yaWhtcnZneHJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1OTk5NjAsImV4cCI6MjA2NjE3NTk2MH0.vb2FDMsVuVxbqHt8ZSIRyag-9XA3pHppWXDywy9Yeaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);